-- Saaya-Inaya Passport Code Migration
-- Run in Supabase SQL Editor: https://supabase.com/dashboard/project/idfnjnflrtodqqpzvbjo/sql/new
--
-- What this does:
-- 1. Creates passport_codes, device_registrations, saaya_events tables
-- 2. SECURITY DEFINER functions: claim_passport_code(), record_saaya_event()
-- 3. Helper: is_passport_owner() for RLS
-- 4. RLS: owner reads all 3 tables, writes happen via service_role (edge functions)
--
-- Safe to re-run (uses IF NOT EXISTS, CREATE OR REPLACE, DROP POLICY IF EXISTS)

-- -----------------------------------------
-- 1. Tables
-- -----------------------------------------

CREATE TABLE IF NOT EXISTS passport_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,  -- 8-char alphanumeric, no ambiguous chars (0/O/1/I/L excluded)
  parent_id uuid REFERENCES parents(id) ON DELETE SET NULL,
  label text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '48 hours'),
  claimed_at timestamptz,
  claimed_by_device text,
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS device_registrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  passport_code text NOT NULL REFERENCES passport_codes(code),
  device_token uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  device_info text,
  registered_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS saaya_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  passport_code text NOT NULL REFERENCES passport_codes(code),
  device_token uuid NOT NULL REFERENCES device_registrations(device_token),
  client_event_id uuid UNIQUE,  -- dedup key, generated by Android client
  timestamp_millis bigint NOT NULL,
  call_type text NOT NULL,
  caller_classification text NOT NULL,
  caller_label text,
  sensitive_app_name text NOT NULL,
  is_overlay_trigger boolean DEFAULT true,
  synced_at timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------
-- 2. Indexes
-- -----------------------------------------

CREATE INDEX IF NOT EXISTS idx_passport_codes_owner ON passport_codes(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_device_registrations_passport_code ON device_registrations(passport_code);
CREATE INDEX IF NOT EXISTS idx_saaya_events_passport_code_synced ON saaya_events(passport_code, synced_at DESC);
CREATE INDEX IF NOT EXISTS idx_saaya_events_device_token ON saaya_events(device_token);

-- -----------------------------------------
-- 3. Enable RLS
-- -----------------------------------------

ALTER TABLE passport_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE saaya_events ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------
-- 4. Helper: is_passport_owner(p_code)
--    Returns true if the current auth user owns the passport code.
-- -----------------------------------------

CREATE OR REPLACE FUNCTION is_passport_owner(p_code text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM passport_codes
    WHERE code = p_code
      AND owner_user_id = auth.uid()
  );
$$;

GRANT EXECUTE ON FUNCTION is_passport_owner(text) TO authenticated;

-- -----------------------------------------
-- 5. RLS Policies
--    Writes go through service_role (edge functions), so only read policies needed.
--    passport_codes also needs INSERT/UPDATE/DELETE for the dashboard owner.
-- -----------------------------------------

-- PASSPORT_CODES: owner full control
DROP POLICY IF EXISTS "Owner manages passport codes" ON passport_codes;
CREATE POLICY "Owner manages passport codes" ON passport_codes FOR ALL
  USING (auth.uid() = owner_user_id)
  WITH CHECK (auth.uid() = owner_user_id);

-- DEVICE_REGISTRATIONS: owner reads via passport_codes join
DROP POLICY IF EXISTS "Owner reads device registrations" ON device_registrations;
CREATE POLICY "Owner reads device registrations" ON device_registrations FOR SELECT
  USING (is_passport_owner(passport_code));

-- SAAYA_EVENTS: owner reads via passport_codes join
DROP POLICY IF EXISTS "Owner reads saaya events" ON saaya_events;
CREATE POLICY "Owner reads saaya events" ON saaya_events FOR SELECT
  USING (is_passport_owner(passport_code));

-- -----------------------------------------
-- 6. claim_passport_code(p_code, p_device_info)
--    Called by edge function with service_role key (no auth.uid()).
--    Validates code, issues device_token, returns it.
--    FOR UPDATE serializes concurrent claims on the same code.
-- -----------------------------------------

CREATE OR REPLACE FUNCTION claim_passport_code(p_code text, p_device_info text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_passport passport_codes%ROWTYPE;
  v_device_token uuid;
BEGIN
  -- Lock the row to prevent two devices claiming simultaneously
  SELECT * INTO v_passport FROM passport_codes
  WHERE code = p_code
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'invalid');
  END IF;

  IF v_passport.revoked_at IS NOT NULL THEN
    RETURN jsonb_build_object('error', 'revoked');
  END IF;

  IF v_passport.expires_at < now() THEN
    RETURN jsonb_build_object('error', 'expired');
  END IF;

  IF v_passport.claimed_at IS NOT NULL THEN
    RETURN jsonb_build_object('error', 'already_claimed');
  END IF;

  -- Issue device token
  v_device_token := gen_random_uuid();

  INSERT INTO device_registrations (passport_code, device_token, device_info)
  VALUES (p_code, v_device_token, p_device_info);

  UPDATE passport_codes
  SET claimed_at = now(), claimed_by_device = p_device_info
  WHERE id = v_passport.id;

  RETURN jsonb_build_object('ok', true, 'device_token', v_device_token);
END;
$$;

-- No GRANT to authenticated — this is called via service_role from edge functions only

-- -----------------------------------------
-- 7. record_saaya_event(...)
--    Called by edge function with service_role key.
--    Validates device_token, checks passport not revoked, inserts event.
--    Dedup via ON CONFLICT DO NOTHING on client_event_id.
-- -----------------------------------------

CREATE OR REPLACE FUNCTION record_saaya_event(
  p_device_token uuid,
  p_client_event_id uuid,
  p_timestamp_millis bigint,
  p_call_type text,
  p_caller_classification text,
  p_caller_label text DEFAULT NULL,
  p_sensitive_app_name text DEFAULT '',
  p_is_overlay_trigger boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_reg device_registrations%ROWTYPE;
  v_passport passport_codes%ROWTYPE;
  v_event_id uuid;
BEGIN
  -- Validate device token
  SELECT * INTO v_reg FROM device_registrations
  WHERE device_token = p_device_token;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'invalid_device_token');
  END IF;

  -- Check passport not revoked
  SELECT * INTO v_passport FROM passport_codes
  WHERE code = v_reg.passport_code;

  IF v_passport.revoked_at IS NOT NULL THEN
    RETURN jsonb_build_object('error', 'passport_revoked');
  END IF;

  -- Insert event (dedup on client_event_id)
  INSERT INTO saaya_events (
    passport_code, device_token, client_event_id,
    timestamp_millis, call_type, caller_classification,
    caller_label, sensitive_app_name, is_overlay_trigger
  )
  VALUES (
    v_reg.passport_code, p_device_token, p_client_event_id,
    p_timestamp_millis, p_call_type, p_caller_classification,
    p_caller_label, p_sensitive_app_name, p_is_overlay_trigger
  )
  ON CONFLICT (client_event_id) DO NOTHING
  RETURNING id INTO v_event_id;

  -- Update last_seen_at
  UPDATE device_registrations
  SET last_seen_at = now()
  WHERE device_token = p_device_token;

  RETURN jsonb_build_object('ok', true, 'event_id', v_event_id);
END;
$$;

-- No GRANT to authenticated — called via service_role from edge functions only
