package com.saaya.app.network

import com.saaya.app.model.ProtectionEvent
import com.saaya.app.util.PassportPreferences
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.util.UUID
import java.util.concurrent.TimeUnit

/**
 * Synchronous HTTP client for Saaya <-> Inaya communication via Supabase Edge Functions.
 *
 * All public methods perform blocking I/O and **must** be called from a background thread.
 */
class SaayaSyncClient(private val passportPrefs: PassportPreferences) {

    private val http: OkHttpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .build()

    private val jsonMediaType = "application/json; charset=utf-8".toMediaType()

    // -- Claim ----------------------------------------------------------------

    /**
     * Claim a passport code generated by the Inaya dashboard.
     * Returns a [ClaimResult] with either the device token or an error.
     */
    fun claimPassport(code: String, deviceInfo: String): ClaimResult {
        val body = JSONObject().apply {
            put("code", code)
            put("device_info", deviceInfo)
        }

        val request = Request.Builder()
            .url("${SupabaseConfig.FUNCTIONS_URL}/claim-passport")
            .header("apikey", SupabaseConfig.ANON_KEY)
            .header("Content-Type", "application/json")
            .post(body.toString().toRequestBody(jsonMediaType))
            .build()

        return try {
            http.newCall(request).execute().use { response ->
                val responseBody = response.body?.string().orEmpty()
                if (response.isSuccessful) {
                    val json = JSONObject(responseBody)
                    val token = json.optString("device_token", "")
                    if (token.isNotBlank()) {
                        ClaimResult.Success(token)
                    } else {
                        ClaimResult.Error("Missing device_token in response", "invalid_response")
                    }
                } else {
                    val json = runCatching { JSONObject(responseBody) }.getOrNull()
                    ClaimResult.Error(
                        message = json?.optString("error", "Claim failed (${response.code})") ?: "Claim failed (${response.code})",
                        errorType = json?.optString("error_type", "http_${response.code}") ?: "http_${response.code}"
                    )
                }
            }
        } catch (e: Exception) {
            ClaimResult.Error(e.message ?: "Network error", "network_error")
        }
    }

    // -- Sync -----------------------------------------------------------------

    /**
     * Sync a single [ProtectionEvent] to Inaya.
     * On failure the event is enqueued locally for later retry via [flushPendingEvents].
     *
     * Returns `true` when the server accepted the event.
     */
    fun syncEvent(event: ProtectionEvent): Boolean {
        val deviceToken = passportPrefs.getDeviceToken() ?: return false
        val eventJson = buildEventJson(event)

        val ok = postEvent(deviceToken, eventJson)
        if (!ok) {
            passportPrefs.enqueueEvent(eventJson.toString())
        }
        return ok
    }

    /**
     * Drain the offline queue, posting each event to the server.
     * Returns the number of events that were synced successfully.
     */
    fun flushPendingEvents(): Int {
        val deviceToken = passportPrefs.getDeviceToken() ?: return 0
        val pending = passportPrefs.dequeueEvents()
        if (pending.isEmpty()) return 0

        var synced = 0
        val remaining = mutableListOf<String>()

        for (raw in pending) {
            val json = runCatching { JSONObject(raw) }.getOrNull()
            if (json == null) {
                // Malformed entry -- drop it.
                continue
            }
            if (postEvent(deviceToken, json)) {
                synced++
            } else {
                remaining.add(raw)
                // Stop retrying after the first failure to avoid hammering a down server.
                remaining.addAll(pending.drop(pending.indexOf(raw) + 1))
                break
            }
        }

        // Replace the queue with whatever was not successfully sent.
        passportPrefs.clearEvents()
        remaining.forEach { passportPrefs.enqueueEvent(it) }

        return synced
    }

    // -- Heartbeat ------------------------------------------------------------

    /**
     * Lightweight ping so Inaya knows the device is alive.
     * Returns `true` on a successful round-trip.
     */
    fun sendHeartbeat(): Boolean {
        val deviceToken = passportPrefs.getDeviceToken() ?: return false

        val request = Request.Builder()
            .url("${SupabaseConfig.FUNCTIONS_URL}/heartbeat")
            .header("apikey", SupabaseConfig.ANON_KEY)
            .header("x-device-token", deviceToken)
            .header("Content-Type", "application/json")
            .post("{}".toRequestBody(jsonMediaType))
            .build()

        return try {
            http.newCall(request).execute().use { it.isSuccessful }
        } catch (_: Exception) {
            false
        }
    }

    // -- Helpers --------------------------------------------------------------

    private fun buildEventJson(event: ProtectionEvent): JSONObject {
        return JSONObject().apply {
            put("client_event_id", UUID.randomUUID().toString())
            put("timestamp_millis", event.timestampMillis)
            put("call_type", event.callType.name)
            put("caller_classification", event.callerClassification.name)
            put("caller_label", event.callerLabel ?: JSONObject.NULL)
            put("sensitive_app_name", event.sensitiveAppName)
            put("is_overlay_trigger", event.isOverlayTrigger)
        }
    }

    private fun postEvent(deviceToken: String, eventJson: JSONObject): Boolean {
        val request = Request.Builder()
            .url("${SupabaseConfig.FUNCTIONS_URL}/sync-saaya-event")
            .header("apikey", SupabaseConfig.ANON_KEY)
            .header("x-device-token", deviceToken)
            .header("Content-Type", "application/json")
            .post(eventJson.toString().toRequestBody(jsonMediaType))
            .build()

        return try {
            http.newCall(request).execute().use { it.isSuccessful }
        } catch (_: Exception) {
            false
        }
    }

    /** Result of a passport claim attempt. */
    sealed class ClaimResult {
        data class Success(val deviceToken: String) : ClaimResult()
        data class Error(val message: String, val errorType: String) : ClaimResult()
    }
}
